### PR TITLE
Initial yarn lock file

### PR DESCRIPTION
**Pull request by Apoorv-Mittal**
Just adding the initial yarn lock file will make some PR requests soon

Edit: This is also one of the first times I am doing a PR.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
Thanks for adding the integrity checks to the lockfile 🎉

Do you have an idea why my yarn version didn't do that by-default?

**Comment by philipp-spiess** [comment]
@Apoorv-Mittal BTW if you wanna help out I have some open issues with my ideas. 🙂 Otherwise let me know what you want to do so we don't end up working on the same things.

And congratulations on your first PR 🎉

**Comment by Apoorv-Mittal** [comment]
I do not know why it did not create a lock file. I found that yarn was having this issue earlier this year but it was fixed. Maybe your yarn is not updated.

I was also thinking on working on the static site generator but I do not have experience using the mentioned technologies. I have used web pack before with a react app. I was thinking of learning Gatsby and implementing that on this project. What do you think ?

**Comment by philipp-spiess** [comment]
I'm not an expert in those projects either but as long as it can generate a static website it should be fine 🙂 I've heard a lot of great thinks about Gatsby so that's for sure a good choice.

If you want to take a look, please comment at the issue (#3) so that nobody else will start working on it at the same time. Thanks ❤️

**Comment by Apoorv-Mittal** [comment]
Okay, Thank you

**Pull request merged**
